/*You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/



class Solution {
public:
    char findTheDifference(string s, string t) {
        int n=s.size();
        int m=t.size();
        unordered_map<char, int>count;
        for(int i=0; i<n; i++){
            count[s[i]]++;
        }
        for(int i=0; i<m; i++){
            if(count[t[i]]==0){
                return t[i];
            }
            count[t[i]]--;
        }
        return ' ';  
    }
};
